### ISSUE TITLE
Don't work when clone

### ISSUE THREAD

**Issue by MrJmpl3** [Learus/react-material-ui-carousel#1]
I clone the project and tried to reproduce.. But I have the error:

Could not find a required file.
  Name: index.html
  Searched in: D:\CARPETA_DE_JOSE\PROYECTOS_JAVASCRIPT\react-material-ui-carousel\public

**Comment by Learus** [comment]
Hello.

This is not supposed to run as an individual project. It is supposed to be imported and used within another one.

If you want to run the demo project, you can go into the demo folder and run `npm start` or `yarn start` from there.

All the code used for the demo is in the demo folder.
