### ISSUE TITLE
Required types for `CarouselStyleProps` seems incorrect

### ISSUE THREAD

**Issue by EliRobinson** [Learus/react-material-ui-carousel#101]
https://github.com/Learus/react-material-ui-carousel/blob/ef8deee03656ad9095b0805df61d5b665ebc867f/src/%40types/react-material-ui-carousel/index.d.ts#L6

I believe these should both be optional. If I pass `CarouselStyleProps`, I shouldn't be expected to pass both.

**Comment by Learus** [comment]
Fixed.

**Comment by EliRobinson** [comment]
Thank you!
