### ISSUE TITLE
[Feature Request] allow for array in IndicatorIcon prop

### ISSUE THREAD

**Issue by bahstud** [Learus/react-material-ui-carousel#107]
I'm trying to build an image gallery where the indicators are thumbnails.  It would be awesome to set a check in the Indicator function component to check if props.IndicatorIcon is an array.  If so, in the loop that builds the indicators use 
```jsx
var item = _react2.default.createElement(
    _IconButton2.default,
    {
        key: i,
        className: className,
        style: style,
        onClick: function onClick() {
            props.press(i);
        },
        size: 'small'
    },
    IndicatorIcon[i]
);
```

**Comment by Learus** [comment]
This is an interesting idea, that I'll have to think about. It will introduce a pretty big change in the code, so I might implement it in version v3.0.0 when that comes out rewriting the library.

Thanks for the suggestion.

**Comment by nicolasmartinez0510** [comment]
Hello! Can I work with this feature? Thanks!

**Comment by Learus** [comment]
@nicolasmartinez0510 Yes, of course, open a new branch and start working on it. I appreciate it :)

**Comment by nicolasmartinez0510** [comment]
Can i ask how i do to test the changes? I dont see tests and i dont know how test what im doing

**Comment by Learus** [comment]
I usually use the `/demo` folder to do my tests. Copy the whole `/src` code into `/demo/src/components/Carousel` and then import the Carousel from the Example components like this:

```js
import Carousel from './Carousel';
```
Edit the copied Carousel code to your liking and test simultaneously.
After you're done update the actual Carousel code by copying back into the `/src` folder.

**Comment by nicolasmartinez0510** [comment]
Hello! I was working on the feature and when passing an image or an array of images to the indicator, the active is not displayed. Is there a solution for that or can I add a prop that sets a shadow?

**Comment by nicolasmartinez0510** [comment]
Hi! ¿ Can I update the documentation to add this feature?

**Comment by Learus** [comment]
@nicolasmartinez0510 
Do a pull request with your changes, whether they are code or documentation changes, so I can review them.
