### ISSUE TITLE
Timeout not implemented

### ISSUE THREAD

**Issue by PiErr0r** [Learus/react-material-ui-carousel#11]
Hello there,
in the documentation there is some talk about the "timeout" prop but upon checking your code the timeout prop for fade and slide is hardcoded to 500 and 200 ms respectively which is a bit too aggressive.
Best regards

**Comment by Learus** [comment]
@PiErr0r 
Hello. Are you using the latest 1.3 version? The "timeout" prop was added on the 1.3 version and does not exist in prior versions.

If you do, take a look at this line of code. (line 120 of Carousel.js in the main component)

```js
const timeout = this.props.timeout !== undefined ? this.props.timeout : (animation === "fade" ? 500 : 200)
```

This does indeed **default** to 500ms or 200ms depending on the animation defined. But it is changable by the "timeout" prop.

**Comment by PiErr0r** [comment]
oh sorry, didn't check the version, I do use v1.3
Thanks for the rapid response, it is much appreciated
