### ISSUE TITLE
[Code Styling] Get rid of redundant ternary operators

### ISSUE THREAD

**Issue by h0tw4t3r** [Learus/react-material-ui-carousel#111]
https://github.com/Learus/react-material-ui-carousel/blob/93ecb0f3f9fcd747c8a196d99c6d908bcdba05da/src/components/Carousel.js#L363-L364
https://github.com/Learus/react-material-ui-carousel/blob/93ecb0f3f9fcd747c8a196d99c6d908bcdba05da/src/components/Carousel.js#L331
https://github.com/Learus/react-material-ui-carousel/blob/93ecb0f3f9fcd747c8a196d99c6d908bcdba05da/src/components/Carousel.js#L326

**Comment by Learus** [comment]
Fixed in v2.3.5.
