### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by omiinaya** [Learus/react-material-ui-carousel#112]
I cannot seem to import "Carousel" to my home component. I get an invalid hook call no matter what I seem to try.

Any ideas?

**Comment by omiinaya** [comment]
This is probably the 5th or 6th time I tried to implement it on a functional component, but of course seconds after I give up and made an issue it decided to magically work... Please close or delete this. Thanks.

**Comment by papiro** [comment]
Mine isn't magically working yet and I've refreshed like 6 times. What did you try differently to get yours to work?

Here's my component:
```
const Ministries = () => {
  return (
    <>
      <Carousel>
        {dinnerImageList.map((image) => (
          <img key={image} src={image} />
        ))}
      </Carousel>
      <ImageList variant="woven" cols={3} rowHeight={200}>
        {sowingImageList.map((image) => (
          <ImageListItem key={image}>
            <img src={image} />
          </ImageListItem>
        ))}
      </ImageList>
    </>
  );
};
```
