### ISSUE TITLE
Material UI 5 support

### ISSUE THREAD

**Issue by CodePsy-2001** [Learus/react-material-ui-carousel#116]
sorry for my poor English.

need to migrate.

------
import @material-ui/core -> import @mui/material
import @material-ui/icons -> import @mui/icons-material
import @mui/core/styles -> import @mui/styles
------

**Comment by CodePsy-2001** [comment]
oh. I checked this PR.
https://github.com/Learus/react-material-ui-carousel/pull/106

Can you write in README.md about mui5 info?
for example, "you need to npm install react-material-ui-carousel@mui5 for mui v5 support"

**Comment by Learus** [comment]
Check out this release

[Github Branch](https://github.com/Learus/react-material-ui-carousel/tree/material-ui-5)
[npm](https://www.npmjs.com/package/react-material-ui-carousel/v/2.3.7-mui5)

I will be stating the existence of this release in the "original" release's README as well.
