### ISSUE TITLE
Material-ui v5 compatibility issue

### ISSUE THREAD

**Issue by USA19** [Learus/react-material-ui-carousel#117]
Material-UI has been updated to version-5 And there is no support for version 5 of material UI.

**Comment by Learus** [comment]
From the docs:

>For Material UI 5 support please use the links below.
[Github Branch](https://github.com/Learus/react-material-ui-carousel/tree/material-ui-5)
[npm package](https://www.npmjs.com/package/react-material-ui-carousel/v/2.3.7-mui5)

Generally use the `@mui` tag to install from npm.
