### ISSUE TITLE
Final step of MUI5 Migration, remove the @mui/styles peer-dep

### ISSUE THREAD

**Issue by aleccaputo** [Learus/react-material-ui-carousel#118]
Per the MUI migration docs, remove all references to `@mui/styles` and remove it from this libs peer dependencies. 
https://mui.com/guides/migration-v4/#migrate-from-jss

Currently in the mui tagged release
Module not found: Can't resolve '@mui/styles' in '/Users/ME/Documents/GitHubREPO/node_modules/react-material-ui-carousel/dist/components'

Extension of #106

**Comment by aleccaputo** [comment]
Seeing that master has has this already, my bad. Can keep this around if you want to link it, otherwise feel free to close it.

**Comment by cortesdev** [comment]
Whats the version that does not require @mui/styles on compiling?
