### ISSUE TITLE
Forced inline style in Carosel container

### ISSUE THREAD

**Issue by Mandlee** [Learus/react-material-ui-carousel#128]
https://github.com/Learus/react-material-ui-carousel/blob/master/src/components/Carousel.tsx#L343

After resizing the browser, the inline style height caused some problems. For instance, when the carousel children component is 300px in desktop size, and resize the browser to mobile view and the children component smaller 250px, the inline style causes empty space (container remains 300px).

It would be great to force somehow to let children's item components manage the height and disable inline height. Is it possible with option property?

**Comment by Mandlee** [comment]
Step to reproduce:
- load in bigger screen size, and resize to mobile view
- load in mobile size and resize to bigger viewport

https://codesandbox.io/s/affectionate-wilson-v9bjs?file=/src/App.js

**Comment by Learus** [comment]
I made an update to fix this issue. Please try v3.0.4. I also forked the sandbox and it works there. 

Please [check it out](https://codesandbox.io/s/react-material-ui-carousel-issue-forked-lr9zl).

**Comment by Learus** [comment]
The only thing that this inline height does, is that it updates the wrapper's height based on the height of the currently active child.

**Comment by Mandlee** [comment]
Everything looks good, thanks for your quick help!
