### ISSUE TITLE
Remove JSS and @mui/styles

### ISSUE THREAD

**Issue by aleccaputo** [Learus/react-material-ui-carousel#130]
The current version of the carousel mui5 branch still has styles as a peer dep and imports mui styles for `makeStyles`.

I had opened #118 for this a while ago, thought i saw the change somewhere, but i must have been mistaken, as the current release still wants me to have styles installed.

Per the mui5 migration docs, the final step is to remove JSS and `@mui/styles` completely.
https://mui.com/guides/migration-v4/#migrate-from-jss

I'd recommend moving to something like [tss-react](https://github.com/garronej/tss-react) for a fairly easy initial transition, then maybe moving to emotion syntax after.

I can try and make a PR if you can give me the preferred way you'd want this done (tss-react vs emotion/styled components syntax)

**Comment by cortesdev** [comment]
Im having an issue that is overriding my buttons styles whenever i call the carousel. Would like to by pass the @mui/styles dependency somehow

**Comment by Mandlee** [comment]
I also reccommend to using `@mui/system` ([docs](https://mui.com/system/basics/)) instead of `@mui/styles`. Currently is supporting, but it's a [legacy](https://mui.com/styles/basics/) in v5.

This package is the last component which using mui styles in my project. It would be great to change this dependency. I can make a PR for changing this dependency.

**Comment by aleccaputo** [comment]
@Mandlee it should probably use the smallest subset of MUI possible (ie not making system a peer dependency). If you want to use system, you should still be able to, it just needs to switch to `styled` from `@mui/material`

**Comment by Learus** [comment]
After reading around a bit on the matter, I believe I prefer `tss-react` since it looks more like what I've been using all this time. @aleccaputo I will start working on it when I have the time, but it would be helpful if you could make a PR on it.

Thanks for the proposal.

**Comment by henry232323** [comment]
I have been playing with v5 styling for my own purposes, please feel free to have a look if it would be of interest
https://github.com/henry232323/react-material-ui-carousel
