### ISSUE TITLE
Index attribute does not update the carousel element being displayed

### ISSUE THREAD

**Issue by oscarychen** [Learus/react-material-ui-carousel#134]
I'm working on something that require the carousel to switch element programmatically, I have something like the following:

```
<Carousel index={activeChapter} autoPlay={false} animation="slide" navButtonsAlwaysInvisible={true} swipe={false}>
  <div key={0}>0</div>
  <div key={1}>1</div>
  <div key={2}>2</div>
</Carousel>
```

The `activeChapter` is a number stored in redux. However when activeChapter updates, the carousel does not switch page.

It appears that the carousel only respects the initial value of `activeChapter` shows the correct corresponding page upon initial render, but would not update when the `activeChapter` changes.

I'm currently using react v17, mui v5.2.

Am I using the `index` attribute wrong, or is this a bug?

Sincerely,
Oscar

**Comment by Learus** [comment]
You're right this is a bug with v3 and will be fixed ASAP.

**Comment by geisterfurz007** [comment]
You can lock your version to 3.0.4 as a workaround.

**Comment by Learus** [comment]
Fixed in 3.1.1

**Comment by geisterfurz007** [comment]
Could this possibly be broken again with 3.2.0?

**Comment by ricale** [comment]
I have the same issue in 3.2.0

**Comment by jacobikedichi** [comment]
I'm seeing the same bug in 3.2.0

@Learus Could you please take a look at this? Thank you very much..

**Comment by akalkid** [comment]
@mui/material   ^5.13.4
react-material-ui-carousel  ^3.4.2

same bug~ not work index
