### ISSUE TITLE
How to change increase the height of the carousel?

### ISSUE THREAD

**Issue by AguChaves92** [Learus/react-material-ui-carousel#136]
I want to increase the height to fie better the information on display

**Comment by AguChaves92** [comment]
I want to increase the "div" whenre the items are displayed

**Comment by kimd345** [comment]
It seems you can control the height of the carousel using the prop indicatorContainerProps and passing in a style object.

**Comment by Learus** [comment]
In general, the carousel does not control its own height. You control the carousel's height, by controlling its children's height. Nevertheless, there are props like `className` that are used to style the carousel externally.

I would urge you to check the children's styles first, before tweaking the carousel's props.

**Comment by AguChaves92** [comment]
THX.
