### ISSUE TITLE
Adding display: 'none' to indicator styles breaks carousel

### ISSUE THREAD

**Issue by givensuman** [Learus/react-material-ui-carousel#138]
Not sure if this is intentional. Adding display: 'none' to indicator styles breaks carousel. This:
```
  <Carousel
  indicatorIconButtonProps={{
      style: {
         display: 'none'
      }
  }}
  >
      {children}
  </Carousel>
```
causes no items to render in the carousel.
Current workaround is 
```
  indicatorIconButtonProps={{
      style: {
         opacity: '0',
         user-select: 'none'
      }
  }}
```
but a more convenient way of disabling indicators might be cool (if it doesn't already exist).

**Comment by Learus** [comment]
There exists the `indicators` boolean that activates or deactivates the indicators. Check the documentation.

**Comment by tufail** [comment]
@Learus  indicators={false} not hiding it. I like to hide the indicators please help
