### ISSUE TITLE
Module not found in react typescript project

### ISSUE THREAD

**Issue by ilyas-muhammad** [Learus/react-material-ui-carousel#14]
I found an error when import this module 
`Module not found: Can't resolve 'react-material-ui-carousel' in '../src/component'`

```
import React from 'react';
import Carousel from 'react-material-ui-carousel';
import { Paper, Button } from '@material-ui/core';
```

Thank you for incoming response

**Comment by Learus** [comment]
For some reason, I did not publish the dist folder with the 1.4 version. Update to the 1.4.2 version and you should be fine. Sorry for the inconvenience.

**Comment by ilyas-muhammad** [comment]
Thank you, will try to upgrade to 1.4.2 version.
