### ISSUE TITLE
Height doesn't change if item content is taller than original item

### ISSUE THREAD

**Issue by Aerophite** [Learus/react-material-ui-carousel#142]
### Issue
If you have multiple carousel items and your first item _isn't_ the tallest, the carousel's height does not increase when it reaches the taller item.

### Recreation
[Sandbox](https://codesandbox.io/s/eager-bogdan-3tqku?file=/src/App.js)

### Expectation
The carousel's height resizes to fit the height of the current item

**Comment by Learus** [comment]
Fixed in v3.3.3

The carousel's height is now exactly the height of the currently active child.
If you want to override this behavior, use the `height` prop to specify an exact height for the carousel.
