### ISSUE TITLE
Misalignment when using SSR hydrate() and webpack --mode=production

### ISSUE THREAD

**Issue by vasansr** [Learus/react-material-ui-carousel#144]
The Carousel shows the items and the nav buttons etc. in incorrect positions, as you can see in the screenshot.  The issue appears ONLY when the webpack mode is `production` AND when we use `hydrate()` to attach the listeners. Using the`development` mode makes the issue disappear. Using `render()` instead of `hydrate()` also makes it go away.

Source code to reproduce the issue can be found in this GitHub repo: https://github.com/vasansr/mui-carousel-example. 

<img width="686" alt="item-1-issue" src="https://user-images.githubusercontent.com/6049234/150677892-71086783-0551-4429-96f4-1edfaed5b7fc.png">
<img width="686" alt="item-2-issue" src="https://user-images.githubusercontent.com/6049234/150677895-17b20e7e-6008-4ee8-b16d-66d4984ecac1.png">
.

**Comment by sedhha** [comment]
Any resolutions yet?

**Comment by acorn421** [comment]
Check this pull request. #143

**Comment by Learus** [comment]
Tested the reproduction project with the updated library version. It renders correctly. Closing this issue.
