### ISSUE TITLE
@material-ui/styles duplication issue

### ISSUE THREAD

**Issue by potier97** [Learus/react-material-ui-carousel#15]
yarn list @material-ui/styles  when i was add material-ui/core, and rsult in :

> ├─ @material-ui/styles@4.9.6
> ├─ @react-material-ui-carrusel
> │  └─ @material-ui/styles@4.9.10

**Comment by Learus** [comment]
Hello.
Since I do not exactly know why and how this is a problem, could you please elaborate?
From my understanding, material-ui/styles is a dependency of the carousel component.
How would that be a problem, and how could I solve it?

**Comment by potier97** [comment]
Hello, that becomes an error at the moment in which the dependency is called the same as the material library or there is a reason that it can break and not apply the classes that are being carried out with this material library, wey.  This seems like a Warning in the Google Chrome debugger so it is necessary to change it to avoid future problems with styles, I solved it by deleting the yarn.lock file and reinstalling the dependencies.

**Comment by Learus** [comment]
Hello, sorry for the late response.

I've looked up the problem, and I have to point out some things.
* The library does not have `@material-ui/styles` as a dependency and is not shipped with it. It does have `@material-ui/core` though, that contains `/core/styles`. I do not know if this could be a problem.
* Check following issues. I believe Issue2 is the warning you are talking about?
  * [Issue1](https://github.com/mui-org/material-ui/issues/15264)
  * [Issue2](https://github.com/mui-org/material-ui/issues/15745)  
* Have you tried duplicate detection tools like `npm dedupe`?

Does this problem get resolved by deleting your lock file and fixing deps on your side, or is there something I should do on my side?

**Comment by Learus** [comment]
Since there hasn't been any activity regarding this issue, I am closing it for now.
