### ISSUE TITLE
MUI 5 compatible version 2 not available via NPM

### ISSUE THREAD

**Issue by 5t33** [Learus/react-material-ui-carousel#152]
`
npm install react-material-ui-carousel@v2mui5 --save

npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-material-ui-carousel@v2mui5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevenstaley/.npm/_logs/2022-02-13T23_38_28_921Z-debug.log
`

**Comment by daveteu** [comment]
`npm i react-material-ui-carousel@2.3.8-mui5`

**Comment by 5t33** [comment]
Thanks, I guess that's just a readme update.
