### ISSUE TITLE
Use map into Carousel

### ISSUE THREAD

**Issue by baptistelechat** [Learus/react-material-ui-carousel#155]
Do you know why I can't use a map function in this case of React structure ?

The components are rendered one below the other and not one after the other.

When I use only the "Map Image" part it works like the documentation says.

```jsx
import Carousel from "react-material-ui-carousel";
...
<Carousel
autoPlay={autoplay}
indicators={false}
onChange={(e) => setCurrentView(e)}
index={currentView}
swipe={false}
>
            <Presentation
              printRef={printRef}
              theme={theme}
              projectName={projectName}
              selectedCity={selectedCity}
              picture={picture}
              picturePosition={picturePosition}
              partner={partner}
            />
            <Maps
              printRef={printRef}
              theme={theme}
              selectedCity={selectedCity}
              projectName={projectName}
              map1={map1}
              map2={map2}
              partner={partner}
            />
            <Zone
              printRef={printRef}
              theme={theme}
              selectedCity={selectedCity}
              projectName={projectName}
              partner={partner}
            />
            {image.map(
              (img, index) => (
                console.log(img),
                (
                  <Image
                    printRef={printRef}
                    theme={theme}
                    selectedCity={selectedCity}
                    projectName={projectName}
                    partner={partner}
                    img={img}
                    key={index}
                  />
                )
              )
            )}
            <Contact
              printRef={printRef}
              theme={theme}
              selectedCity={selectedCity}
              projectName={projectName}
            />
</Carousel>
```

**Comment by Learus** [comment]
I believe your code should work by the looks of it.
If you have time, I'd like you to make a CodeSandbox with your code to test it out properly. I can't know what your specific components do exactly.

**Comment by Vishal-Kank** [comment]
Facing same issue could you please make a CodeSandbox
I am making a ticket system can see only first row rest are getting rendered but not visible

**Comment by Vishal-Kank** [comment]
Hi just tried this one 
`<Carousel autoPlay={false} 
        indicatorContainerProps={{
          style: {
              marginTop: height
          }
        }}
      >`
need to calculate the height of all the elements which we get in,  after using map.
you can also use some fix number in place of height.
[([baptistelechat](https://github.com/baptistelechat))]

**Comment by Learus** [comment]
Check out if the problem is solved when updating to v.3.3.3.

**Comment by baptistelechat** [comment]
yes, now it work for me thanks ! 👨‍💻🙏🎉
