### ISSUE TITLE
Unexpected console.log 

### ISSUE THREAD

**Issue by bennaaym** [Learus/react-material-ui-carousel#162]
https://github.com/Learus/react-material-ui-carousel/blob/51f2724e1c69c43c0d08adbdaaa40b20757e20b1/src/components/CarouselItem.tsx#L40

Hey, The above console.log wasn't removed from the production version, that's causing unwanted logs when the user drag  and drop CarouselItem.

I think that's a small bug and I wanted to report it. 

Great package :)

**Comment by Learus** [comment]
Removed in v3.3.3.
