### ISSUE TITLE
Programmatically setting index doesn't work

### ISSUE THREAD

**Issue by dmelching** [Learus/react-material-ui-carousel#163]
According to the readme, it should be possible to use the prop `index` to programmatically set the active child. I saw this working in earlier 2.x.x versions. But it doesn't work in 3.2.0.

**Comment by SargunNarula** [comment]
I also encountered this same issue in the latest version, have you found any solution to it yet?

**Comment by austingandy** [comment]
+1 -- I'm also seeing this in 3.2.0 as well

**Comment by Learus** [comment]
A fix is being worked on, along with other features. Stay tuned.

**Comment by Learus** [comment]
Fixed in v3.3.3.
