### ISSUE TITLE
React 18 compatibility

### ISSUE THREAD

**Issue by ximex** [Learus/react-material-ui-carousel#174]
Add react 18 dependencies:
```json
"react": "^18.0.0",
"react-dom": "^18.0.0",
```

**Comment by cortesdev** [comment]
Still not working, whats needed to fix it?

**Comment by ximex** [comment]
i don't know. i didn't do any more tests. i only saw that the dependencies need an update

**Comment by ChrisSamo632** [comment]
For me, the problem was that this library pulls in an older version of `react` and `react-dom` (17.0.2) compared with that use by my project (18.0.0)

https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react suggests that maybe `react`/`react-dom` should be specified as `peerDependencies` rather than `dependencies` within this library (I don't know whether that's correct/something to change here)?

As my project is being built with `yarn`, I was able to set `resolutions` in my `package.json` to include
```json
    "resolutions": {
        "react": "^18.0.0",
        "react-dom": "^18.0.0"
    }
```

This appears to have allowed the `<Carousel />` to work again for me without any further changes.

**Comment by cortesdev** [comment]
Thanks

> For me, the problem was that this library pulls in an older version of `react` and `react-dom` (17.0.2) compared with that use by my project (18.0.0)
> 
> https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react suggests that maybe `react`/`react-dom` should be specified as `peerDependencies` rather than `dependencies` within this library (I don't know whether that's correct/something to change here)?
> 
> As my project is being built with `yarn`, I was able to set `resolutions` in my `package.json` to include
> 
> ```json
>     "resolutions": {
>         "react": "^18.0.0",
>         "react-dom": "^18.0.0"
>     }
> ```
> 
> This appears to have allowed the `<Carousel />` to work again for me without any further changes.

Thanks brother, working really well

**Comment by BertiRean** [comment]
> For me, the problem was that this library pulls in an older version of `react` and `react-dom` (17.0.2) compared with that use by my project (18.0.0)
> 
> https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react suggests that maybe `react`/`react-dom` should be specified as `peerDependencies` rather than `dependencies` within this library (I don't know whether that's correct/something to change here)?
> 
> As my project is being built with `yarn`, I was able to set `resolutions` in my `package.json` to include
> 
> ```json
>     "resolutions": {
>         "react": "^18.0.0",
>         "react-dom": "^18.0.0"
>     }
> ```
> 
> This appears to have allowed the `<Carousel />` to work again for me without any further changes.

Could you tell in which package.json file I need to the change?. In my project package.json or where?

**Comment by ximex** [comment]
should be this if you use `npm` instead of `yarn`. but didn't test it
```json
  "overrides": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }
```
works only with `npm@^8.3`
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by Bodrie** [comment]
> should be this if you use `npm` instead of `yarn`. but didn't test it
> 
> ```json
>   "overrides": {
>     "react-material-ui-carousel": {
>       "react": "^18.0.0",
>       "react-dom": "^18.0.0"
>     }
>   }
> ```
> 
> works only with `npm@^8.3` https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Yes, this works!**  
Just don't forget to delete the `package-lock.json` and then run `npm install`

Cheers to @ximex  :)

**Comment by Learus** [comment]
The library now supports react 18 from version 3.4.0 onwards.
Thanks for being patient everyone and sorry for the wait.

**Comment by elijah-pl** [comment]
@Learus what about MUI 5 branch? Seems like it still does not support React 18.
