### ISSUE TITLE
How to use sx prop?

### ISSUE THREAD

**Issue by doinby** [Learus/react-material-ui-carousel#178]
Can someone give me an example of how to use sx to change carousel's root styling?

Trying to write this:
`sx={{ border: 1, display: "flex"}}`
Results in:
`Property 'sx' does not exist on type 'IntrinsicAttributes & CarouselProps'.`

Thanks.

**Comment by kb-0311** [comment]
passin the `sx` prop as <String, String> key value pairs. 

`sx={{ "border": "1", "display": "flex"}}`

now pass this a a prop to `<Carousel sx=.{ {......} }/>`

**Comment by Learus** [comment]
@doinby Without being exactly sure what the problem is, or if what @kb-0311 is saying helped you out, what version of the carousel are you using?

The sx prop is introduced after v3.0.0. Are you perhaps on version v2?
