### ISSUE TITLE
how to disable the z-index

### ISSUE THREAD

**Issue by Vishal-Kank** [Learus/react-material-ui-carousel#179]
`<div class="css-14j5k7k">
     <div draggable="false" style="user-select: none; touch-action: pan-y; transform-origin: 50% 50% 0px;">
        <div style="position: relative; opacity: 1; z-index: 1; transform: none;">`
here the z-index is set automatically how do we disable it 
I have a loader with a higher z-index value but due to this zindex value contents from Carousel overlapse the loader.

**Comment by jzhmrtn** [comment]
Hello! Did you find a way to change it?
