### ISSUE TITLE
Error while using in latest MUI

### ISSUE THREAD

**Issue by sagarpadiya6** [Learus/react-material-ui-carousel#182]
I am getting the below error using this library in the latest version on mui.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/102873513/167300354-326d24b5-6a90-4aa6-af2a-5d9fed45e016.png">

As soon as I add the library and add the below component I get this error.

```jsx
import React from "react";
import Carousel from "react-material-ui-carousel";
import { Paper, Button } from "@mui/material";

function Example(props) {
  var items = [
    {
      name: "Random Name #1",
      description: "Probably the most random thing you have ever seen!",
    },
    {
      name: "Random Name #2",
      description: "Hello World!",
    },
  ];

  return (
    <Carousel>
      {items.map((item, i) => (
        <Item key={i} item={item} />
      ))}
    </Carousel>
  );
}

function Item(props) {
  return (
    <Paper>
      <h2>{props.item.name}</h2>
      <p>{props.item.description}</p>

      <Button className="CheckButton">Check it out!</Button>
    </Paper>
  );
}

export default Example;

```

**Comment by kunaltyagi9** [comment]
@sagarpadiya6 I am facing the same issue, is your issue resolved? I @earthddx I am using `react 18.1.0` and `react-material-ui-carousel 3.3.3` and its not working, It is throwing the same error

**Comment by SangeetAgarwal** [comment]
@kunaltyagi9 how can I use your forked repo in my project?

**Comment by sagarpadiya6** [comment]
@kunaltyagi9  I ended up using a different carousel. But i will try the bumping version thing suggested by @earthddx

**Comment by Learus** [comment]
Since this seems to be a React 18 issue, I will be closing this.
The carousel now supports React 18 from version v3.4.0 onwards.
