### ISSUE TITLE
CarouselItem.js file to stop console.log numbers. control bar when clicked, not working.

### ISSUE THREAD

**Issue by janie-lee-developer** [Learus/react-material-ui-carousel#186]
version I'm using:     "react-material-ui-carousel": "^3.4.1",

I have 2 issues.

issue 1: 
See attached pic. CarouselItem.js is console.logging 'divRef.current.offsetHeight'. How can we stop this? I need console.log to test other things and this is pushing up my logs every second.
<img width="538" alt="Screen Shot 2022-05-30 at 4 13 51 PM" src="https://user-images.githubusercontent.com/58411107/171057084-576671cf-e556-4682-a878-2bf0ceb7eb1a.png">
<img width="750" alt="Screen Shot 2022-05-30 at 4 13 38 PM" src="https://user-images.githubusercontent.com/58411107/171057089-404ea587-b418-4091-9dda-d4acbd383f7b.png">

issue 2:
When I click the other lighter grey buttons to go to a specific slide, it doesn't work. This dots are not clickable. How can I add a function so the slide renders the one that I click on the circle?

Here's my code.
<img width="232" alt="Screen Shot 2022-05-30 at 4 13 59 PM" src="https://user-images.githubusercontent.com/58411107/171057247-484d033b-dc85-4fbb-9dc3-c9fd68715ab8.png">

<img width="939" alt="Screen Shot 2022-05-30 at 4 43 46 PM" src="https://user-images.githubusercontent.com/58411107/171057245-7b6fb301-d53b-4606-9414-0fdd9bb94351.png">

Thank you in advance!!

**Comment by Learus** [comment]
`console.log` issue is fixed, and published in v3.4.2.

As for the indicator issue, they should work properly, given the code you posted. It sometimes happens with CRA apps, but it's not the library's issue. The whole page becomes unclickable or unresponsive to any user input. I'm not sure what causes it, but I do not think it's the carousel's fault.

**Comment by janie-lee-developer** [comment]
I just updated the version as you recommended and it went away! Thank you! 

Ahhh.. issue 2 is unfortunate to hear.. thank you so much!
