### ISSUE TITLE
Flash of background between transitions

### ISSUE THREAD

**Issue by damian-tripbuddi** [Learus/react-material-ui-carousel#20]
Firstly, great job. It's been hard to find something suits my needs, I'm really liking what I see.

My only issue is that on each slide transition, the card being removed is hidden abruptly, and the background is shown as the next card slides or fades into view.

Would it be possible to animate the current card away?

Again, great job.

**Comment by Learus** [comment]
Hello! Thank you for your kind words.

The problem you are facing has been a problem since the very beginning, and its cause is the way I have currently coded the render method. I wanted to solve this for a very long time, but I just haven't found the time to do so. It is on my todo list and in a high priority. 
Since this component has been seeing a lot of traction lately, I will try to do it asap.

Stay tuned! I hope it will be ready in the next few days.

**Comment by Learus** [comment]
Hello again.

Changes are in. The Carousel Items are now being animated out when the next one is supposed to appear.

Check out the [demo page](https://learus.github.io/react-material-ui-carousel/) and let me know if the current solution solves your issue.

**Comment by damian-tripbuddi** [comment]
That's a great turn around.

I could see that it was by using the hidden property that was causing the complete removal of the previous slide.

I've had a look at your change, and how you're added some state to manage the transition better... but unfortunately I don't think that this has worked.

For me, the demo page looks exactly the same as before.

I had a bit of look at creating a fix yesterday, and I think it's going to need a little more work to get this working correctly... for the fade effect, both the previous and the next slides need to occupy the same space while the opacity of each transitions. For them to both occupy the same space, it probably involves some absolute positioning, which I think would impact on how the slide transition is working.

Anyhow, if I get some time, I'm happy to help out to get this right... but I would hate to lose the simplicity of your solution. So I'm not sure if the change is worth it.

**Comment by Learus** [comment]
What I did is, I implemented a timeout, where the element waits to be animated out before it stops rendering. The next element also waits to be rendered accordingly.

Funny thing is, that I faced the same issues as you did, while I was implementing the change.

The timeout solution solves every one of them and is fully customizable, using the timeout prop as explained in the documentation (same as the MaterialUI Transition API timeout prop)

As for the reason why you're not seeing it on the demo page is that I forgot to `npm update` the demo app to use the 1.5.0 version after I implemented the changes.

Check the [demo](https://learus.github.io/react-material-ui-carousel/) out for real this time. :)

**Comment by damian-tripbuddi** [comment]
Oh I see the change now.

It's a fantastic improvement.

Ideally though, for a clean transition, the transitions would need to overlap. With slide, the current would  slide out to the left, and at the same time the new slide comes in from the right. For fade instead of fading to white, it would fade to the new image. All of this requires a bigger change.which would require a bigger change.  

I'll see what I can come up with as a solution, and I'll share it with you.

I really like this last update though... it looks better.

**Comment by Learus** [comment]
Yes indeed, it would be a great feature. There should be a nice way to go at it, but I can't come up with something simple at the moment. I'll keep this issue open until it is done.

By the way, for future reference, **you can remove** the "exit animation" by customizing the timeout prop. Specifically, you can define the prop as

```jsx
<Carousel timeout={{
    appear: number,
    enter: number,
    exit: number   // <-- Set this to 0
}} />
```

**Comment by viniciusaugutis** [comment]
@Learus this is good for me too.

**Comment by Learus** [comment]
Fixed in [version 3](https://www.npmjs.com/package/react-material-ui-carousel/v/3.0.2).
