### ISSUE TITLE
Displaying one Item at time

### ISSUE THREAD

**Issue by 00ricardo** [Learus/react-material-ui-carousel#201]
Hello, how are you guys? I appreciate your work in this project! I'm trying to intregrate it in my app with success but with 1 issue in particular that i want to discuss and solve.

I want to display an array of MUI Avatars in Carousel as Facebook did (example below)
![image](https://user-images.githubusercontent.com/61938096/194347787-c15bdcbb-aaeb-4381-83ac-0e4cc7a1dbdb.png)

At the moment I have part of this feature but only one Avatar at time, how can i display, lets say 4/5 avatars and not just one? I can only see others is I swipe out.

![image](https://user-images.githubusercontent.com/61938096/194347043-9e3964b5-c012-4729-a0fd-ec859eb1544c.png)
![image](https://user-images.githubusercontent.com/61938096/194347087-febbc4e9-c8f6-47e8-b640-13953f9f35cf.png)

Maybe any property that I'm missing.

![image](https://user-images.githubusercontent.com/61938096/194348401-ec8e79aa-d77c-4dad-b9b0-07e23eeeb893.png)

Thanks guys, hope I make it clear and easy to debug.

**Comment by M-Hamza-Aslam** [comment]
hey! were you successful? can you tell me which property allows to show multiple items at a time ?

**Comment by MohamedBenTaher** [comment]
Hi @00ricardo, I'd really appreciate it if you can share how did you solve this issue, thanks for your help

**Comment by 00ricardo** [comment]
> Hi @00ricardo, I'd really appreciate it if you can share how did you solve this issue, thanks for your help

Hi @MohamedBenTaher . I hope you're doing great, so sorry for my late response, hope I can still help. 

After further investigation I was not able to solve my original problem with this library so I decided to replace it by another one which is capable to render multiple content. It was very easy to adapt the code and integrate the new library (React Indiana - Drag & Scroll).

I'm not aware whether the developers already took a look into this topic but for my experience it's not possible to allow multiple content inside the carrousel (yet).

I hope you can move on with your solution. Best of luck.


Ref: https://www.npmjs.com/package/react-indiana-drag-scroll
