### ISSUE TITLE
custom button added to the corner of the card is not clickable because hidden div with the right arrow

### ISSUE THREAD

**Issue by cesarpachon** [Learus/react-material-ui-carousel#219]
hello,
I am trying to add a small "x" button on the top-right corner of my cards in order to allow users to dismiss the announcements that they don't want to see.
something like:
-carrousel
-- Card //the announcement container
--- Button //the button in the corner

The problem is that a transparent div appears in the right side as soon as you move the mouse there, making impossible to click the button. I tried with z-index with no success (hidden div has z-index=1 and MUI buttons have z-index=1500 but that doesn't seems to have any effect.

In this screenshot I deformed the button so a side of it lies outside the invisible div, in that part the click works:

![image](https://github.com/Learus/react-material-ui-carousel/assets/2874200/428ec9ee-1ad8-4af1-ae3b-2f58f479ccfe)

I appreciate any suggestion about how to implement this feature.

**Comment by Learus** [comment]
Hi. Try using thee `fullHeightHover` boolean prop. That's exactly the use case for it.

**Comment by cesarpachon** [comment]
Thanks @Learus it worked!
