### ISSUE TITLE
StartIndex

### ISSUE THREAD

**Issue by Mrbeyond** [Learus/react-material-ui-carousel#22]
Assuming there is an array of data to display, I really want to specify the first data to come up on the carousel. For instance, if I click on a particular image, I want it to be the first Item to come up before other images, simply put it should be the first index to show.  React-bootstrap carousel has this functionality. I really like the how next and prev icon on hover that this exhibits but had to suspend it for now due to the index set back. Thanks and looking forward to having a reply very soon Sir.

**Comment by Learus** [comment]
Hello there.

I added a prop called "startAt", that is exactly the functionality you are asking for. Assuming the children are an array of data, the carousel displays the item at the "startAt" index of the array.

By default, if the startAt index is bigger than the array's length, the carousel begins at the last child.
You can disable this functionality though, by setting the "strictIndexing" prop to false.

If the children prop is not an array but is a single value, startAt will become 0.

You can find everything I am talking about in the 1.5.1 version of the carousel.

**Comment by Mrbeyond** [comment]
Thanks a lot Sir.
Actually I later worked my way round  it by finding the selected index and reposition the array with splice. It worked well but this startAt prop will surely reduce the code and implement it soon. Thanks a lot Sir.
