### ISSUE TITLE
Does this lib support touch navigation/ touch swipe.

### ISSUE THREAD

**Issue by manoj-mass** [Learus/react-material-ui-carousel#24]

**Comment by Learus** [comment]
No, it does not. It will in the future though. It is on my roadmap.

**Comment by Learus** [comment]
It is done. 
The carousel now supports swipe left and swipe right. Swipe left calls next() function, while swipe right calls prev() function.

I might add customizability to these functionalities, and even give access to the swipe handlers, but let me know if you think that would be a valuable thing to add.

Remember to update your installation to v1.6.0.

**Comment by manoj-mass** [comment]
Thanks.
