### ISSUE TITLE
Callbacks for next/previous transition

### ISSUE THREAD

**Issue by j1m-renwick** [Learus/react-material-ui-carousel#25]
I wanted to do some conditional rendering on the page outside of this component, based on the current item active in the carousel - i.e, update their state based on carousel next/previous item transitions.  Couldn't see anything like this in the code - is this something you'd consider merging if I submitted a PR for it?  Sounds fairly trivial, but might need your input on what data you'd like passed to the callback function (...assuming you want this implemented at all...!)

**Comment by Learus** [comment]
I can see the use case for something like this for sure.

I wouldn't replace the existing next() and prev() functions though, with user-given callbacks, if that's what you are thinking. What I would do is, I would call the user callbacks after all state changes have been fired (or before, depending on what the use case is). So, basically "add" the user callback to the already defined next() and prev() functions.

> is this something you'd consider merging if I submitted a PR for it?

Yes, I would, but I would also be able to implement this personally. 
As you pointed out, it seems like a very trivial thing to implement, as long as we think through when exactly the user callback should be called.

**Comment by j1m-renwick** [comment]
Ok cool, well I'm happy to leave this with you as you're better placed to make the decisions on callback function arguments, when to call it etc. without having to go through me.  But if I can be a help then let me know :)

**Comment by Learus** [comment]
It is done. Check the documentation for more details. Remember to update your installation to v1.6.0.

**Comment by j1m-renwick** [comment]
awesome, thanks a lot!
