### ISSUE TITLE
If last Item of Children Array Deleted, no Child is Displayed

### ISSUE THREAD

**Issue by jbgrunewald** [Learus/react-material-ui-carousel#27]
I'm using the carousel for a dynamic array of children that can be grown and individual children deleted. The carousel doesn't work as I would expect if I delete the last child of the array. I would prefer if it either circled back to the first child, or to the prev child. Right now it doesn't select anything and you need to manually select from the button bar.

**Comment by Learus** [comment]
Hello.
Would you be so kind as to post a simple reproduction of what you're doing?
Just the base idea. It would help a lot in internal testing, and to understand exactly the problem you are describing.

**Comment by johnsintal** [comment]
I may have fixed this by using a key for the main Carousel element so that it rebuilds an instance instead of updates.

```
 <Carousel
        autoPlay={false}
        timeout={200}
        key={taxItemFormLocalState.documents.length}
....
```

**Comment by Learus** [comment]
This is fixed.
