### ISSUE TITLE
npm run build auto-bind error

### ISSUE THREAD

**Issue by djbuen** [Learus/react-material-ui-carousel#29]
yo @Learus , Im trying to build my app but i got this error. Im using latest version of react-material-ui-carousel(1.6.0), auto-bind(2.1.1). Any idea?

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/react-material-ui-carousel/node_modules/auto-bind/index.js:4

Read more here: http://bit.ly/2tRViJ9

**Comment by Learus** [comment]
Hi there!
Have you been able to solve the issue? As far as I understand reading what you shared, you seem to have an old version of `react-scripts`. Did you try updating it (if it's indeed old)? In any case, this does not seem to be an issue with this specific library.

**Comment by djbuen** [comment]
Hello Learus, I have resolved the issue already. Updating the react-scripts should fix it. Thanks man @Learus !
