### ISSUE TITLE
Update Example:  "key" prop' warning

### ISSUE THREAD

**Issue by fishme** [Learus/react-material-ui-carousel#31]
for all that have the same error with 
`Unable to eliminate 'Each child in a list should have a unique "key" prop' warning.`

will fix it:
```
<Carousel>
  {
          items.map(item => <React.Fragment key={item.id}><Item item={item} /></React.Fragment>)
        }
</Carousel>
```

**Comment by Learus** [comment]
I created this example to explain the Carousel in a very simple and concise way. I'm thinking the "key" prop adds a layer of complexity for less advanced React users.

On the other hand, people should learn to use React correctly, and one could say that using the `Array.map` function to render elements is more "advanced" usage anyway.

What are your thoughts on it?

**Comment by Learus** [comment]
Added the key prop to the example.
