### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by nickschuster** [Learus/react-material-ui-carousel#32]
Hi there
Are there any plans to fix this in future updates?

Reference: https://fb.me/react-strict-mode-find-node

Great package!
Cheers

**Comment by Learus** [comment]
Hello.
As far as I'm aware this is a bug in the MaterialUI library. Specifically, I've noticed it appears when using the `<Fade>` component. I'm reading it appears in other cases as well. Hopefully, it gets fixed on its own. There should be no warning in the production build though, so don't worry about it (for now).

**Comment by nickschuster** [comment]
Alright, I checked and you are right it does not appear in production. I guess I will keep an eye on the MaterialUI change log. Thank you for the help!

**Comment by illume** [comment]
This is supposed to be fixed in Material UI 5. 

See https://next.material-ui.com/guides/migration-v4/#non-ref-forwarding-class-components
