### ISSUE TITLE
react-scripts should go in dev dependencies

### ISSUE THREAD

**Issue by charbugs** [Learus/react-material-ui-carousel#34]
Not sure but I think react-scripts should go to devDependencies, shouldn't it? Otherwise npm installs a whole bunch of packages on your consumers machines they probably don't need (~100MB).

**Comment by Learus** [comment]
Hello there.
I'm actually not sure either. Can someone perhaps confirm this?

**Comment by Learus** [comment]
react-scripts moved to devDependencies.
