### ISSUE TITLE
How to get onChange event for slides in autoPlay or on indicator press

### ISSUE THREAD

**Issue by lukeharrisontravis** [Learus/react-material-ui-carousel#35]
Love this plugin! 

wondering how to do trigger a change slide event on press of one of the indicator buttons. I know there's a next prev trigger on the arrow buttons on the side, which fires a next and prev event on the carousel but is there any way to get one on the indicator dots? Either A. IF you are using your default carousel dots or B. If you came up with your own custom dots

**Comment by lukeharrisontravis** [comment]
@Learus got a one line solution to this problem if I can get access to make a pr request.

**Comment by Learus** [comment]
Hello there. Thanks for the suggestion.
I don't think adding CSS classes would be the best solution for this problem, though. It would be much better if I added callbacks, similar to the `next` and `prev` props. Maybe even just integrate the indicator press callbacks into the same props. It would be much simpler that way.
Stay tuned in any case!

P.S. Feel free to make any pull requests you like. :)

**Comment by lukeharrisontravis** [comment]
Yeah you're 100% right Learus! My solution does virtually nothing for the state management of the buttons. In the above solution I was actually trying to solve for a different problem (which i failed to mention and forgot to say anything about, lol).  

I was dealing with the problem of not being able to style the "active" dot, because the classname is changed by mui and ends up being unpredictable. My little classname addition merely gives people access to pure css styling of the active indicator (since consumers don't have access to the indicators as elements in the component, and since mui changes the "active" class name when it gets compiled to jssXXX". 

But yeah, for the problem of triggering actions on indicator press, you're right on the money, and the indicators would need some new callbacks...

I tried to push up a pr but it said i needed access rights. Do I need that?

**Comment by Learus** [comment]
I added the `onChange` prop. It works similarly to the `next` and `prev` props, though it gets called every time a slide changes.

**Important note**: The `next` and `prev` callbacks **override** the `onChange` prop. That means, that if for example both `onChange` and `next` are defined, the "next" button will only call the `next` prop and not the `onChange`.  
The `onChange` callback will only be called when pressing an indicator.

If `next` or `prev` props are not defined but `onChange` is, then the `onChange` callback will be called **in every situation**. That means in both next/prev buttons **and** the indicator press.

Make sure to update to version 1.7.1 or higher.
