### ISSUE TITLE
Being able to style the "active" indicator dot

### ISSUE THREAD

**Issue by lukeharrisontravis** [Learus/react-material-ui-carousel#36]
Thanks again for this learus!

I was dealing with the problem of not being able to style the "active" dot, because it only has a classes.active class name, which gets changed by mui on build and ends up being unpredictable. it would be great to give devs access to a static, pure css class name on the active indicator dot, for purposes of styling the active indicator (since consumers don't have access to the indicators as elements in the component, and since mui changes the "active" class name when it gets compiled to jssXXX".

**Comment by lukeharrisontravis** [comment]
Possible solution
<img width="718" alt="Screen Shot 2020-07-13 at 7 51 15 PM" src="https://user-images.githubusercontent.com/67061337/87458637-1d58b680-c5bf-11ea-876e-a256d8e5076f.png">

**Comment by Learus** [comment]
Hello again.

I added the props:
* `indicatorProps: {className: string, style: React.CSSProperties}`
* `activeIndicatorProps: {className: string, style: React.CSSProperties}`

You can use those to customize the indicators.

Make sure you use version 1.7.1 or greater.

**Comment by foubei** [comment]
activeIndicatorProps className prop is styling the inactive indicators instead. Is it a bug or something?

**Comment by Learus** [comment]
@foubei 
Yes, it is a bug! Thanks for noticing. I'm solving it in v1.8.3.
