### ISSUE TITLE
Conflicting Styles with Material UI - Use Peer Dependency Instead?

### ISSUE THREAD

**Issue by johnsintal** [Learus/react-material-ui-carousel#37]
## Problem
Using `<Carousel>` and Material UI at the same time causes styles to clash, breaking Material UI

### Without `<Carousel>` rendered in app
![image](https://user-images.githubusercontent.com/2457368/87471165-e64cca00-c5eb-11ea-95a1-9daa5de491ee.png)

### With `<Carousel>` rendered in app.
![image](https://user-images.githubusercontent.com/2457368/87471229-02e90200-c5ec-11ea-807c-06c036a9d0b5.png)

## How to reproduce
```
npx create-react-app my-app
cd my-app
npm start
```

Add the following to `package.json`
```
   "@material-ui/core": "4.10.2",
    "react-material-ui-carousel": "1.6.0",
```

Modify App.js

```
import React from 'react';
import './App.css';
import Button from "@material-ui/core/Button";
import Carousel from "react-material-ui-carousel";
import Box from "@material-ui/core/Box";

function App() {
  return (
    <div >
      <Box p={5} >
        <Button variant="contained" color="primary" type="submit">
          Submit
        </Button>
        <Carousel>
          <div key={1}>item 1</div>
          <div key={2}>item 2</div>
        </Carousel>

      </Box>
    </div>
  );
}

export default App;
```

`yarn install & yarn start` Start the app and observe the clashing styles on `.MuiButtonBase-root` and etc...

## Possible Fix
Move Material ui and icons to peer dependencies. See https://github.com/mui-org/material-ui/issues/15610#issuecomment-568452026

i.e.
```
"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "gh-pages": "^2.2.0",
    "@material-ui/core": "^4.10.2",
    "@material-ui/icons": "^4.9.1"
  },
  "peerDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "@material-ui/core": "^4.10.2",
    "@material-ui/icons": "^4.9.1"
  }
```

**Comment by Learus** [comment]
I'm not sure if putting MUI in the peer-dependencies is the right approach to this problem since this library is supposed to be used outside of MUI projects as well. I don't expect the user to have installed MUI beforehand necessarily, and this makes installation harder.
Have you tried resolving conflicts in your package-lock file? What happens if you delete and `npm install` again?

**Comment by fmartins-andre** [comment]
I have a similar issue. When the carousel is rendered it's changing the BaseButton Root style from MUI. As result any MUI MenuItem is broken.

**Comment by daveteu** [comment]
I'm having the same problem.

> I'm not sure if putting MUI in the peer-dependencies is the right approach to this problem since this library is supposed to be used outside of MUI projects as well. I don't expect the user to have installed MUI beforehand necessarily, and this makes installation harder.
> Have you tried resolving conflicts in your package-lock file? What happens if you delete it and `npm install` again?

You named this repo material-ui-carousel so I'm sure most people who came upon this package are using MUI, don't you agree?

**Comment by Learus** [comment]
> You named this repo material-ui-carousel so I'm sure most people who came upon this package are using MUI, don't you agree?
I guess you're right.

In any case though, how come some projects have this problem while others don't? Couldn't it be something else entirely? I was thinking of versioning problems withing the package.json or package-lock.json.
I will change it to a peerDependency and see how it goes.

I will keep this issue open for now. Test it and let me know.
