### ISSUE TITLE
X-scroll appears on slide animation

### ISSUE THREAD

**Issue by pedroAndrad1** [Learus/react-material-ui-carousel#38]
For a second, the x-scroll appears on the slide animation. Is there a way around this?

**Comment by pedroAndrad1** [comment]
I added " overflowX:'hidden' " to Carousel. It Worked but the animation is not the same

**Comment by Learus** [comment]
Hello.

I've been aware of this issue for a little while now, but I haven't been able to find a simple solution yet. It will be fixed eventually.

**Comment by Learus** [comment]
It is fixed.
Remember to update your `react-material-ui-carousel` version to v1.8.1.
