### ISSUE TITLE
Hide left/right nav buttons

### ISSUE THREAD

**Issue by DevPhil77** [Learus/react-material-ui-carousel#40]
Is there a way to hide the left/right nav buttons like you can hide the indicators?

I did get around this by accessing it through the classes on Carousel, just thought it would be a nice add on.

The reason I needed this is similar to your first example where the left/right nav buttons are covering up a button within the carousel.

**Comment by DevPhil77** [comment]
I did get around this by accessing it through the classes on Carousel, just thought it would be a nice add on.

The reason I needed this is similar to your first example where the left/right nav buttons are covering up a button within the carousel.

**Comment by Learus** [comment]
Hello there!

No, there is no "official" way to completely hide the nav buttons as of yet. I will add a Boolean prop to handle that feature.

Stay tuned!

**Comment by Learus** [comment]
It is done.
You can use the `navButtonsAlwaysInvisible` prop to do what you're asking for.
Remember to update your react-material-ui-carousel to v1.8.1.

**Comment by DevPhil77** [comment]
Awesome, appreciate the quick response.
