### ISSUE TITLE
Carousel keeps focus

### ISSUE THREAD

**Issue by Marcioshub** [Learus/react-material-ui-carousel#41]
When i put the carousel at the top of the page then scroll all the way down it scrolls back to the top of the page after each image change the carousel makes.

**Comment by Learus** [comment]
Hello there, sorry for the late response.

That's not something I have experienced while using the carousel in projects. There is no code, that specifically scrolls inside the library. This leads me to think, that there is something happening in your specific usage of the carousel, meaning the children, the wrapper, or something else.

Could you perhaps share part of your code to shed some light on the situation?

**Comment by Learus** [comment]
I will close this due to inactivity, assuming the bug was unrelated to the carousel.
