### ISSUE TITLE
Is there a way to control the index via dropdown

### ISSUE THREAD

**Issue by aldrinjavier** [Learus/react-material-ui-carousel#43]
If there's a way to set indexState via a dropdown select  that I could pass to as props, that would be awesome

**Comment by Learus** [comment]
Hello, and sorry for the late response.
What exactly do you mean by "indexState"? What exactly are you looking to do?
From what I can understand, you're looking for a way to set the active child as a prop? Is that correct?

**Comment by olivermolina** [comment]
@Learus How to set the active child as a prop?

**Comment by Learus** [comment]
@olivermolina 
You can't right now. The only thing that comes close to that is the `startAt` prop.
If this is something that you find useful, I will implement it.

Stay tuned.

**Comment by dohomi** [comment]
@Learus I think it would make totally sense to programatically set the index state from outside the component. Probably an `index` prop would be great to set the current index. This would bring back the same behaviour as `SwipeableViews` has

**Comment by Learus** [comment]
@dohomi I can see some uses out of a feature like this. But there are some important questions that need answering if something like this is to be implemented, given that this library is a carousel at its core.
Let's say there's an `index` prop that sets the current slide.
* What should happen if you click the next button (or prev doesn't matter)
    * Should it ignore the button press?
    * Should it continue from the current index?

The second approach seems much more logical. But if you think about it, isn't this what the `startAt` prop does? Or at least what it should be doing?

An elegant way to solve this, is to extend the functionality of the `startAt` prop. RIght now, it only matters in the construction phase of the carousel. What I could do, is check whether this prop value changes between updates, and forcefully set the active slide to that value. Everything else would continue to work as it does now. But if at some point you would want to force-set the current slide, that would do the trick, without breaking anything else.
Maybe also change the name from `startAt` to `index` or something that more accurately describes above functionality.

What's your opinion on the idea? Any other suggestions or counter-points?

**Comment by dohomi** [comment]
@Learus what you describe is probably the perfect fit. I am using `SwipeableViews ` currently and this is how that library is implemented. So a rename of `startAt` => `index` and watch changes on index might be the best way to do this. It is important that all other functionalities like next button should continue to work as expected. You probably could internally set `index` on buttons/indicators press to streamline the functionality.

**Comment by Learus** [comment]
Finally! I have found the time to implement this feature.
Version 2.1.0 now implements exactly what I'm describing above and I've renamed the `startAt` prop to `index`.

For more information on this new `index` prop check the [documentation](https://github.com/Learus/react-material-ui-carousel/blob/master/README.md).

**Comment by EArminjon** [comment]
Just in time when i need it :) !

Ty guys
