### ISSUE TITLE
TS Typings Are Incorrect

### ISSUE THREAD

**Issue by tzarger** [Learus/react-material-ui-carousel#45]
In the current version, the index.d.ts is incorrectly defined.

        indicatorProps: {className: string, style: React.CSSProperties},
        activeIndicatorProps: {className: string, style: React.CSSProperties},

Those should be nullable it seems. With Typescript, it is complaining if you don't define those.

Is this intentional?

**Comment by Learus** [comment]
You are definitely correct! I will make them optional props.
Stay tuned.

**Comment by Learus** [comment]
The changes are in. Make sure to update to v1.8.2

**Comment by tzarger** [comment]
@Learus Thanks so much for the quick response!

**Comment by stevemckenzie** [comment]
This issue exists with [`CarouselStyleProps`](https://github.com/Learus/react-material-ui-carousel/blob/master/src/%40types/react-material-ui-carousel/index.d.ts#L5) as well.
