### ISSUE TITLE
Internal error?

### ISSUE THREAD

**Issue by KevinBurton** [Learus/react-material-ui-carousel#46]
Taken from the examples I have a react component that implements a CarouselBanner. This seems to work fine as long I am running locally but when I go to bundle it up for production via 'yarn build'  (which triggers `gatsby build`) my `gatsby build` throws the error

```
failed Building static HTML for pages - 16.475s

 ERROR #95313 

Building static HTML failed for path "/dashboard/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  332 |                 indicators ? _react2.default.createElement(Indicators, {
  333 |                     classes: classes,
> 334 |                     length: this.props.children.length,        
      | ^
  335 |                     active: this.state.active,
  336 |                     press: this.pressIndicator,
  337 |                     indicatorProps: this.props.indicatorProps, 


  WebpackError: TypeError: Cannot read property 'length' of undefined  

  - Carousel.js:334 
    node_modules/react-material-ui-carousel/dist/components/Carousel.js    :334:1
```

Notice that the error is coming from node_modules which this component. Right?

**Comment by Learus** [comment]
Though I am not sure what exactly gatsby does when building, this error probably suggests that the carousel element does not have any children.
I will make it so, the carousel doesn't crash when it has no children, but make sure you add children to it.

Stay tuned.

**Comment by Learus** [comment]
The changes are in. Make sure to update to v1.8.2.
