### ISSUE TITLE
is there any way to customise nav buttons or hide them from hover as well?

### ISSUE THREAD

**Issue by ganesh-papola** [Learus/react-material-ui-carousel#51]
Wanted to hide nav buttons forever even from hover or any class or css based config there?
I dont want to show them any ways..

**Comment by Learus** [comment]
Hi.
There is a prop called `navButtonsAlwaysInvisible` that implements the wanted behavior.

**Comment by ganesh-papola** [comment]
@Learus 
that still shows on hover on left or right side of the carousel.
```navButtonsAlwaysInvisible``` this property will hide hide from the screen but once you hover on sides it'll display again..
I wanted to hide them forever even from hover

**Comment by Learus** [comment]
That's weird for sure.
The buttons are not rendered if the `navButtonsAlwaysInvisible` prop is true, as shown below.

![image](https://user-images.githubusercontent.com/33862893/93021480-75299300-f5eb-11ea-9502-8c66fc30d05b.png)

The behavior you're describing:
> navButtonsAlwaysInvisible this property will hide from the screen but once you hover on sides it'll display again.

is the default behavior of the carousel.
What version of the carousel do you have installed?
Could you share part of your code?

**Comment by ganesh-papola** [comment]
@Learus My bad, i was using both props ```navButtonsAlwaysInvisible``` and ```navButtonsAlwaysVisible``` with wrong values may be that was causing the issue..

Thanks for the response and code
