### ISSUE TITLE
indicator container custom css support

### ISSUE THREAD

**Issue by djbuen** [Learus/react-material-ui-carousel#52]
is there a way we can customize the indicators container?

**Comment by Learus** [comment]
No, there is no way to do that as of yet. What are you looking to do?

**Comment by djbuen** [comment]
i need to reposition the indicators within the image or item container, something like this https://drive.google.com/file/d/1hfiOLJ_ohIgGZwZ-XiAg3zkrIR9WtSGn/view?usp=sharing

**Comment by Learus** [comment]
Hello again. I added support for issues like yours.
You can use the `indicatorContainerProps` to add a `className` or `style` prop to the indicators wrapper.

To achieve your wanted styling, you could do 
```js
indicatorContainerProps={{style: {position: "absolute", bottom: 0}}}
```
But that's just a suggestion. Use it as you please.

**Comment by djbuen** [comment]
thank you very much man @Learus , i though you were busy i could have just pr that change
