### ISSUE TITLE
TypeScript Required Prop indicatorContainerProps Should be Optional

### ISSUE THREAD

**Issue by michaelshum321** [Learus/react-material-ui-carousel#53]
hi, I'm using this project with typescript, and I think the Typescript interface `CarouselProps` has a required prop that should be optional.

The member in question is `indicatorContainerProps` - none of the examples provided have this member set, and the code works when making the field optional. 

Here's the CodeSandbox, using c-r-a w/ typescript. https://codesandbox.io/s/kind-matsumoto-tt16n

you can see that there's a typescript compiler error when you hover over the `<Carousel>` tag on line 52 in `App.tsx` but the page is still functional and the Carousel works as-expected.

Let me know if this is as intended and I can throw in a fix to the typing (just making `indicatorContainerProps` optional) or whatever fits you :)

**Comment by Learus** [comment]
As I mentioned in the PR, I was careless when implementing that change. Thanks.
