### ISSUE TITLE
respect slide direction on swipe left/right

### ISSUE THREAD

**Issue by dohomi** [Learus/react-material-ui-carousel#57]
Hello,

thanks for this nice library. I think visually it would make sense if the slide direction is reverted if "prev" is triggered. Currently the slide is always to left, but if you swipe backwards I think to right might be little bit more consistent.

**Comment by Learus** [comment]
I'm working on it. It's gonna be in the next update. Stay tuned.

**Comment by Learus** [comment]
Turns out it was easier to implement than what I initially thought. Thanks for pointing it out. A change like this adds a lot of polish to a library like this. It is working on v2.0.0. I will publish on npm whenever it's up again.

**Comment by gakin95** [comment]
is this right?  <Carousel 
      className={classes.slide}
      animation={"slide"}
      navButtonsAlwaysVisible={true} > //is this line right? the navButtonsAlwaysVisible is not working on my project. Apart from this this carousel is the best material ui carousel i have seen so far. nice one bro
        {data.map(event => <FeaturedEvent
        key={event.id}
          category={event.category}
          host={event.host}
          title={event.title}
          image={event.image}
          amount={event.amount}
          numOfRegAttendees={event.numOfRegAttendees}
          date={event.date}
          time={event.time}
        />)}
        </Carousel>

**Comment by Learus** [comment]
@gakin95 
I've recreated your problem as a [new issue](https://github.com/Learus/react-material-ui-carousel/issues/58). Please don't post irrelevant questions in already existing issues.
In any case, I'm closing this issue since the problem it's referring to has been solved.
