### ISSUE TITLE
navButtonsAlways visible is not working for me

### ISSUE THREAD

**Issue by Learus** [Learus/react-material-ui-carousel#58]
is this right?  <Carousel 
      className={classes.slide}
      animation={"slide"}
      navButtonsAlwaysVisible={true} > //is this line right? the navButtonsAlwaysVisible is not working on my project. Apart from this this carousel is the best material ui carousel i have seen so far. nice one bro
        {data.map(event => <FeaturedEvent
        key={event.id}
          category={event.category}
          host={event.host}
          title={event.title}
          image={event.image}
          amount={event.amount}
          numOfRegAttendees={event.numOfRegAttendees}
          date={event.date}
          time={event.time}
        />)}
        </Carousel>

_Originally posted by @gakin95 in https://github.com/Learus/react-material-ui-carousel/issues/57#issuecomment-699609570_

**Comment by Learus** [comment]
@gakin95
I'm gonna try to reproduce the bug on my end, and see if it's working normally. Meanwhile, send me more of your code.

**Comment by gakin95** [comment]
ok , i'll do that right away

**Comment by gakin95** [comment]
import React, { useState } from "react";
import {
  Grid,
  Typography,
  FormControl,
  Select,
  MenuItem,
} from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";
import { FeaturedEvent } from "../singleItem";
import Carousel from 'react-material-ui-carousel';

const useStyles = makeStyles((theme) => ({
  category: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  formControl: {
    width: 265,
    height: 61,
    display: "block",
    //float:'right'
  },
  selectContainer: {
    backgroundColor: theme.palette.primary.main,
    borderRight: "1px solid #fff",
    color: "#fff",
  },
  selectContainerText: {
    paddingTop: 40,
    paddingBottom: 40,
  },
  slide: {
    width:'80%',
    margin:'auto'
  }
}));

function BrowseCategory({data}) {
  const [category, setCategory] = useState("Browse category");
  const [open,setOpen] = useState(true);
  const handleCategoryChange = (e) => {
    setCategory(e.target.value);
    console.log(category);
  };
  const classes = useStyles();
  return (
    <Grid container spacing={3} >
      <Grid item xs={12} className={classes.category}>
        <Typography variant="h5">Featured Events</Typography>
        <FormControl className={classes.formControl}>
          <Select
            labelId="title-type"
            id="title"
            value={category}
            onChange={handleCategoryChange}
            variant="outlined"
            style={{ width: "100% !important" }}
            // margin="dense"
            fullWidth
          >
            <MenuItem value="Browse category">Browse category</MenuItem>
            <MenuItem
              value="Music"
              onClick={() => console.log("music was clicked")}
            >
              Music
            </MenuItem>
            <MenuItem value="Commedy">Commedy</MenuItem>
            <MenuItem value="Show">Show</MenuItem>
            <MenuItem value="Travel">Travel</MenuItem>
            <MenuItem value="Education.">Education.</MenuItem>
          </Select>
        </FormControl>
      </Grid>
      <Grid item xs={12} >
        <div >
      <Carousel 
      className={classes.slide}
      animation={"slide"}
      navButtonsAlwaysVisible={true} >
        {data.map(event => <FeaturedEvent
        key={event.id}
          category={event.category}
          host={event.host}
          title={event.title}
          image={event.image}
          amount={event.amount}
          numOfRegAttendees={event.numOfRegAttendees}
          date={event.date}
          time={event.time}
        />)}
        </Carousel>
        </div>
      </Grid>
    </Grid>
  );
}

export default BrowseCategory;

**Comment by gakin95** [comment]
import React, { useState } from "react";
import {
  Grid,
  Typography,
  FormControl,
  Select,
  MenuItem,
} from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";
import { FeaturedEvent } from "../singleItem";
import Carousel from 'react-material-ui-carousel';

const useStyles = makeStyles((theme) => ({
  category: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  formControl: {
    width: 265,
    height: 61,
    display: "block",
    //float:'right'
  },
  selectContainer: {
    backgroundColor: theme.palette.primary.main,
    borderRight: "1px solid #fff",
    color: "#fff",
  },
  selectContainerText: {
    paddingTop: 40,
    paddingBottom: 40,
  },
  slide: {
    width:'80%',
    margin:'auto'
  }
}));

function BrowseCategory({data}) {
  const [category, setCategory] = useState("Browse category");
  const [open,setOpen] = useState(true);
  const handleCategoryChange = (e) => {
    setCategory(e.target.value);
    console.log(category);
  };
  const classes = useStyles();
  return (
    <Grid container spacing={3} >
      <Grid item xs={12} className={classes.category}>
        <Typography variant="h5">Featured Events</Typography>
        <FormControl className={classes.formControl}>
          <Select
            labelId="title-type"
            id="title"
            value={category}
            onChange={handleCategoryChange}
            variant="outlined"
            style={{ width: "100% !important" }}
            // margin="dense"
            fullWidth
          >
            <MenuItem value="Browse category">Browse category</MenuItem>
            <MenuItem
              value="Music"
              onClick={() => console.log("music was clicked")}
            >
              Music
            </MenuItem>
            <MenuItem value="Commedy">Commedy</MenuItem>
            <MenuItem value="Show">Show</MenuItem>
            <MenuItem value="Travel">Travel</MenuItem>
            <MenuItem value="Education.">Education.</MenuItem>
          </Select>
        </FormControl>
      </Grid>
      <Grid item xs={12} >
        <div >
      <Carousel 
      className={classes.slide}
      animation={"slide"}
      navButtonsAlwaysVisible={true} >
        {data.map(event => <FeaturedEvent
        key={event.id}
          category={event.category}
          host={event.host}
          title={event.title}
          image={event.image}
          amount={event.amount}
          numOfRegAttendees={event.numOfRegAttendees}
          date={event.date}
          time={event.time}
        />)}
        </Carousel>
        </div>
      </Grid>
    </Grid>
  );
}

export default BrowseCategory;

**Comment by gakin95** [comment]
<img width="1440" alt="Screenshot 2020-09-28 at 13 31 42" src="https://user-images.githubusercontent.com/51079405/94428610-cf773780-0145-11eb-9c8e-da98f590c1d3.png">

**Comment by gakin95** [comment]
<img width="1440" alt="Screenshot 2020-09-28 at 13 40 31" src="https://user-images.githubusercontent.com/51079405/94428683-fdf51280-0145-11eb-9345-121c881a5bbe.png">

**Comment by Learus** [comment]
Hi again.
I can't seem to reproduce the bug on my end. All seems to be working fine... and that's suspicious.
May I ask what happens when you hover on the sides of the carousel? Any errors in the console? What are you using to implement your app (CRA, Next, Gatsby, ...)?

**Comment by gakin95** [comment]
Thank you very much Loannis for helping out,
it is working fine when i hover on the side of the carousel and it is not
giving any error in the console. i am implementing my app with nextjs

**Comment by davwheat** [comment]
I'm having the same exact issue using Gatsby!

**Comment by EvoTech3** [comment]
This is because: https://github.com/Learus/react-material-ui-carousel/blob/master/src/components/Carousel.js#L94
PR that fixes it can be found here: https://github.com/Learus/react-material-ui-carousel/pull/62

**Comment by gebigoma** [comment]
Also not working for me. 

@EvoTech3 I tried your fix locally and it doesn't seem to change anything. 

Just to be 100% sure, this issue is about the buttons in the screenshot? Basically working like the demo. Sorry to be seem pedantic, my brain is completely fried. This sanity check is more for me. 😄 
![Screen Shot 2020-10-05 at 6 59 08 PM](https://user-images.githubusercontent.com/30670003/95150403-f254ad80-073c-11eb-8cc0-182cc016e6b1.png)

**Comment by gebigoma** [comment]
I did this: probs not a good idea but I need to push to Prod in the next couple days:

```    
carousel: {
  overflow: 'visible',
      '& > :nth-of-type(2)': {
        right: -36,
        '& > :nth-of-type(1)': {
          opacity: 1
        }
      }
    }

**Comment by Learus** [comment]
Fixed by @EvoTech3. I merged the PR. Let me know if it's still not working.

**Comment by gebigoma** [comment]
Yay I updated the library and it works as intended now. Thanks @EvoTech3 and @Learus !

**Comment by gakin95** [comment]
thanks
