### ISSUE TITLE
Custom Navigation Buttons and Indicators

### ISSUE THREAD

**Issue by gggiiia** [Learus/react-material-ui-carousel#60]
i think that a prop to set a custom element for managing buttons and bullets would be really helpfull, i imagine that the prop is a function that returns the component and has as arguments the function to navigate and possibly other info, like the current index

**Comment by Learus** [comment]
Hello.
What is it that you would like to customize in the nav buttons?
Styling? Functionality?
Right now there are 3 props that handle the latter case:
* `next`
* `prev`
* `onChange`

Refer to the documentation see more about them.

Is there something more in regards to functionality customization that can't be done using those props? If so, please let me know.

In the former case (styling) I will add customization in the future. Stay tuned.

**Comment by detoner777** [comment]
Thanks for your work, I'm want to use this in my project. Can you please show simply how next/prev props works with custom buttons? Best!

**Comment by Learus** [comment]
@detoner777 
Thanks!
Firstly, at the time of writing, there is no way to visually customize the buttons. This feature is not finished yet.
As for the usage of `next`, `prev`, and `onChange`, it is shown in the documentation.
Specifically:

## Next & Prev Usage

```jsx
    <Carousel
        next={ (next, active) => console.log(`we left ${active}, and are now at ${next}`); }
        prev={ (prev, active) => console.log(`we left ${active}, and are now at ${prev}`); }
    >
        {...}
    </Carousel>

    // OR

    <Carousel
        next={ () => {/* Do stuff */} }
        prev={ () => {/* Do other stuff */} }
    >
        {...}
    </Carousel>

    // And so on...
```

Note: `onChange` works in a similar fashion. See below.

| Prop name                 | Type                                                               | Default     | Description                                                                                                                                                                                                                                                                                                                                              |
| ------------------------- | ------------------------------------------------------------------ | ----------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| onChange                  | `(index: number, active: number) => void` (internally: `Function`) | `() => {}`  | Function that is called **after** internal `next()`, `prev()`, and `pressIndicator()` methods. First argument is the child **we are going to display**, while the second argument is the child **that was previously displayed**. Will only get called on `next()` if `props.next === undefined` and only get called on `prev()` if `props.prev === undefined` |
| next                      | `(next: number, active: number) => void` (internally: `Function`)  | `() => {}`  | Function that is called **after** internal `next()` method. First argument is the child **we are going to display**, while the second argument is the child **that was previously displayed**                                                                                                                                                            |
| prev                      | `(prev: number, active: number) => void` (internally: `Function`)  | `() => {}`  | Function that is called **after** internal `prev()` method. First argument is the child **we are going to display**, while the second argument is the child **that was previously displayed**    

Do you have more questions regarding those?

**Comment by gggiiia** [comment]
> Hello.
> What is it that you would like to customize in the nav buttons?
> Styling? Functionality?
> Right now there are 3 props that handle the latter case:
> 
> * `next`
> * `prev`
> * `onChange`
> 
> Refer to the documentation see more about them.
> 
> Is there something more in regards to functionality customization that can't be done using those props? If so, please let me know.
> 
> In the former case (styling) I will add customization in the future. Stay tuned.

style is the main goal of this issue, but being able to pass a custom component would make the carousell a lot more flexible and open it up to customization, like material-ui does with a lot of its component, i don't see why this cannot be implemented.

**Comment by Learus** [comment]
Of course, it can be implemented. But adding a customizable button className prop is much easier to implement than to allow for any component. The buttons are much integrated into the whole carousel's functionality, so it is not an easy decision to make since the props I provide and explain above already provide the functionality you're looking for. It will be a larger change than it might appear at first. I will test it out though.

**Comment by bklever** [comment]
getting around this by using `button[aria-label="Previous"]` to style until there is option to pass down classnames to the buttons

**Comment by Victor-Varghese** [comment]
can some one provide a snippet on how to customize prev and next buttons ? I need to change width,height and border-radius

**Comment by BleddP** [comment]
Hi @Victor-Varghese 

You could add the below in a CSS style sheet, although the optional styling changes are very basic. For full styling control I would wait for the author to release a new version with styling options. In case you still wish to try:

`/* Button test */
button[aria-label='Next'] {
  background-color: darkgreen;
  color: #fff;
  opacity: 1;
  border-radius: 5px;
  width: 20px;
  height: 20px;
}

button[aria-label='Previous'] {
  background-color: darkgreen;
  color: #fff;
  opacity: 1;
  border-radius: 5px;
  width: 20px;
  height: 20px;
}`

Hope this helps for now.

**Comment by akinncar** [comment]
I think it is a good idea,I try to styling the existing button but it doesn't have the behavior that I expect.

Is it possible to get the "next" function to execute in another place of the code? I think if have a function in referance of the component, could be help the people to call this functions in other components.

**Comment by agustif** [comment]
fwiw I just wanted to change color of the navButtons so I went for a css override. Leaving the whole thing in case someone needs it.

```
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
    monospace;
}


.Carousel-root-17 {
  overflow: hidden;
  position: relative;
}
.Carousel-indicators-18 {
  width: 100%;
  margin-top: 10px;
  text-align: center;
}
.Carousel-indicator-19 {
  color: #afafaf;
  cursor: pointer;
  font-size: 15px;
  transition: 200ms;
}
.Carousel-indicator-19:hover {
  color: #1f1f1f;
}
.Carousel-indicator-19:active {
  color: #1f1f1f;
}
.Carousel-active-20 {
  color: blue  !important;
}
.Carousel-buttonWrapper-21 {
  top: calc(50% - 70px);
  height: 100px;
  position: absolute;
  background-color: transparent;
}
.Carousel-buttonWrapper-21:hover .Carousel-button-23 {
  filter: brightness(120%);
  opacity: 0.4;
  background-color: blue !important;
}
.Carousel-fullHeightHoverWrapper-22 {
  top: 0 !important;
  height: calc(100% - 20px - 10px) !important;
}
.Carousel-button-23 {
  top: 30px;
  color: white;
  cursor: pointer;
  margin: 0 10px;
  position: relative;
  font-size: 30px;
  transition: 200ms;
  background-color: blue  !important;
}
.Carousel-button-23:hover {
  opacity: 0.6 !important;
}
.Carousel-fullHeightHoverButton-24 {
  top: calc(50% - 20px) !important;
}
.Carousel-buttonVisible-25 {
  opacity: 0.6;
}
.Carousel-buttonHidden-26 {
  opacity: 0;
}
.Carousel-next-27 {
  right: 0;
}
.Carousel-prev-28 {
  left: 0;
}
```
PS: Just make sure to import that css into your app and use !important to take precedent over carousel rules.

So in my case to just customize navButtons background color I added to my index.css
```
.Carousel-active-20 {
  color: blue  !important;
}
.Carousel-buttonWrapper-21:hover .Carousel-button-23 {
  background-color: blue !important;
}
.Carousel-button-23 {
  background-color: blue  !important;
}

```
A nice solution might be extra option props like showNavButtons={true, {color: "blue|#fff|rgba(9,0,0)", size: "{small|medium|large|px|em}}

or something like that, for now I'll refrain from opening a PR for this since my CSS hack works for me, hopefully for you too if you're reading me =)

Have a nice day and thank you very much @learus for this awesome lib!

**Comment by Learus** [comment]
Thanks, @agustif for your kind words!

This is indeed a workaround, but you have to keep in mind how styles work in Material UI. Specifically, the `-13` or -26` you see as a suffix to the classes in the dev tools is dynamic and **is not the same** for every environment. I can't guarantee that this will work for anything else other than your specific **development** environment.

To anyone that wants to try this, check your dev tools first before copying the code @agustif has posted, for any differences in the class names.

**Comment by agustif** [comment]
> Thanks, @agustif for your kind words!
> 
> This is indeed a workaround, but you have to keep in mind how styles work in Material UI. Specifically, the `-13` or -26` you see as a suffix to the classes in the dev tools is dynamic and **is not the same** for every environment. I can't guarantee that this will work for anything else other than your specific **development** environment.
> 
> To anyone that wants to try this, check your dev tools first before copying the code @agustif has posted, for any differences in the class names.

Whoops, certainly didnt think about that!!

Thanks for the heads up, maybe I shall open that PR at the end...

**Comment by hyprstack** [comment]
Is there a way to move the buttons to the bottom of the crousel and remove the background color using the `className` prop?

**Comment by Learus** [comment]
Navigation Buttons/Indicators customization is finally implemented! 
Check the [Readme](https://github.com/learus/react-material-ui-carousel/README.md) for more information.

Thank you for your contributions, everyone.
