### ISSUE TITLE
index.js:1 Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by josoroma** [Learus/react-material-ui-carousel#64]
Hi hackers!

I am hitting this error:

![image](https://user-images.githubusercontent.com/69951/95218241-5022dd00-07b1-11eb-9aa4-64186af34010.png)

![image](https://user-images.githubusercontent.com/69951/95218394-76e11380-07b1-11eb-9c6a-c5ef9700ce51.png)

![image](https://user-images.githubusercontent.com/69951/95218437-7fd1e500-07b1-11eb-96f3-546fa6ee090c.png)

**Comment by Learus** [comment]
Duplicate of #32
