### ISSUE TITLE
How to generate new items once I reach the end of carousel? (Question)

### ISSUE THREAD

**Issue by nmalchy** [Learus/react-material-ui-carousel#67]
Hello, awesome component, the data I am working with uses pages in the api JSON, so when I reach the end of the carousel, I would like it to make a new api call to populate the carousel with new values, but I don't really know how to set a conditional for when I reach the end of the carousel, and the API does not allow me to get all the items for all pages, is there a way to re-populate the carousel when I reach the end so that when it goes back to the start there are new items?

**Comment by Learus** [comment]
Hello.
It's a good idea to use the `next` prop for this. The documentation says about the `next` prop:
> Function that is called after internal next() method. First argument is the child we are going to display, while the second argument is the child that was previously displayed

You could say that whenever the first argument is equal to the carousel's length, then do an API request. Here's some example code (Don't quote me on it, its just off the top of my head):
```jsx
<Carousel
    next={(nextChild, activeChild) => {
        if (nextChild === length - 1)
        {
             // API Request that sets state
        }
    }}
>
    {// Children}
</Carousel>
```

**Comment by nmalchy** [comment]
That's a great strategy, however, it doesn't seem like the next and prev props are working for me... I just copy and pasted the example from the documentation and it doesn't seem to console.log, everything else works though, am I using them incorrectly somehow? Here's a look at my code: https://github.com/nmalchy/react-movie-suggester/blob/master/src/components/MovieForm.tsx

Carousel is at the bottom of the file and the Item is near the top if that's affecting it

**Comment by Learus** [comment]
Turns out there was a bug in how the next and prev props were initialized. It should work now. Please, update to version 2.0.2.
Thanks for pointing it out!
