### ISSUE TITLE
Adding key binding to next prev?

### ISSUE THREAD

**Issue by nmalchy** [Learus/react-material-ui-carousel#69]
Hello, wondering how/if I can bind left & right arrow keys on my keyboard to the next and prev buttons?

**Comment by Learus** [comment]
Hi there!
No, at the time of writing you can't do that. I'm working on an update to the carousel, where it will allow you to set the current child on your own. When that's implemented (soon™), you will be able to create functions that statefully change the current index. You will then be able to bind those functions to the keys you want.
Stay tuned!

**Comment by nmalchy** [comment]
Cool, thanks for the update

**Comment by Learus** [comment]
I've implemented the change I was talking about. Check #43 and the `index` prop explanation in the [documentation](https://github.com/Learus/react-material-ui-carousel/blob/master/README.md).

**Comment by nmalchy** [comment]
Hey, sorry to keep bothering you, but I read the documentation and tried to bind a keypress so as to change the index but I don't see how I can do it, maybe I'm not very experienced with React, but I don't know where to make the function to change the index, I can't do it in the onChange, and I can't do it in the next/prev because those only work when I click on the nav buttons, I tried to make a function outside the component to change a state variable on keypress (const [carouselIndex, setCarouselIndex] = useState(0)) in the index prop like index={carouselIndex} but I just get the error below before I can even do anything: 
(JSX attribute) index: number
No overload matches this call.
  Overload 1 of 2, '(props: CarouselProps, context?: any): ReactElement<any, any> | Component<CarouselProps, any, any> | null', gave the following error.
    Type '{ children: Element[]; navButtonsAlwaysVisible: true; autoPlay: false; timeout: number; index: number; animation: "fade"; next: (next: any) => void; prev: (prev: any) => void; }' is not assignable to type 'IntrinsicAttributes & CarouselProps'.
      Property 'index' does not exist on type 'IntrinsicAttributes & CarouselProps'.
  Overload 2 of 2, '(props: PropsWithChildren<CarouselProps>, context?: any): ReactElement<any, any>

Any idea how to proceed? I am using version 2.1.1

**Comment by Learus** [comment]
A simple idea is to make a document event listener listen to the key presses.
Check out this [sandbox](https://codesandbox.io/s/react-material-ui-carousel-navigate-with-arrow-keys-example-h6l4h?file=/src/App.tsx) I made to solve this. It uses Create React App with typescript (I assume you're using CRA with typescript).
Using the left and right arrow keys moves the carousel around.

**Comment by RitikPandey1** [comment]
Is carousel desgin is responsive(for smaller screen)?

**Comment by Learus** [comment]
@RitikPandey1 I don't see how this is a relevant follow-up to this issue. Please, open a new issue.

**Comment by nmalchy** [comment]
@Learus Thanks for the pointing me in the right direction with your sandbox example!
