### ISSUE TITLE
#indicators

### ISSUE THREAD

**Issue by arezooalipanah** [Learus/react-material-ui-carousel#7]

**Comment by arezooalipanah** [comment]
hi loannis
how we can change indicators ?

**Comment by arezooalipanah** [comment]
for example this css is ok 
.Indicators svg {
  width: 42px;
  height: 4px;
  border-radius: 2px;
  background-color: #183c97;
  margin: 0 2px;
};

.Indicators svg circle {
  visibility: hidden;
}
.Carousel .Indicators .Indicator.Active {
  background: #ffbd4c;
}
thanx

**Comment by Learus** [comment]
Yes, that css will work. You can override any css, given you know the classNames. I will make it so you can also override it with the "style" property, directly from react. The "withStyles", "createStyles" e.t.c from Material UI should also work.

**Comment by arezooalipanah** [comment]
Thank you for your efforts and your advice :))))))

**Comment by anjali0508** [comment]
<div class="Carousel-indicators-4"> This is a sub class generated within Carousel. How can I make changes to the styles for this class?
