### ISSUE TITLE
Disable navigation button onEnd

### ISSUE THREAD

**Issue by jupardo** [Learus/react-material-ui-carousel#70]
Hi!

How can I disable left/right button when the user reaches the end of the items in the carousel?

Also, can I change the styling of nav arrows? It seems that arrows are not vertically centered.

**Comment by Learus** [comment]
Hello there.
You can't do that simply with a prop or something like that, and I can't think of a way to do it using the `next` or `prev` props. It's a good idea that I should implement.
As for the navigation arrows, no, not yet.

**Comment by Learus** [comment]
From version 2.2.0, this feature is implemented using the `cycleNavigation` prop, a boolean value, that stop the carousel from cycling around itself when it reaches the end or center.
