### ISSUE TITLE
How to specify that how many items should be visible at a time?

### ISSUE THREAD

**Issue by sandeepsingh2383** [Learus/react-material-ui-carousel#71]
Hi,

I have gone through the README section and unable to find a way to specify how many items should be visible at a time.

Thanks

**Comment by Learus** [comment]
Hello.
There is no functionality that handles this case in the carousel. It can be easily handled outside of the carousel The carousel renders all of its children. If say the children are an array of objects, you could only use a part of that array using the array prototype functions to slice or filter it.

**Comment by lephleg** [comment]
I don't think I understood your answer. If lets say I have 12 items in an array, is there a functionality that allows me to display 3 of them each time I click Next or shall I merge them manually in 4 sets and pass the new array to the carousel?

**Comment by Learus** [comment]
Yeap, that's exactly what you'd have to do.

**Comment by C-alcium** [comment]
Thanks for the answer, this should probably be put in the docs up front, I was slightly confused about that.
