### ISSUE TITLE
How to pause autoPlay when hovering over a slide ?

### ISSUE THREAD

**Issue by mbennani** [Learus/react-material-ui-carousel#73]
Hi, is there a way to pause autoPlay when hovering over the active slide ?

**Comment by Roman-Cecile** [comment]
Hi, Have you test with `onClick={() => setAutoplay(!autoPlay)}` ?

**Comment by Learus** [comment]
Hello.
I had this implemented long ago, but it wasn't working apparently. It is fixed now on  ^v2.1.2. Sorry for the late response and thanks for pointing out.
