### ISSUE TITLE
Please add CHANGELOG

### ISSUE THREAD

**Issue by natterstefan** [Learus/react-material-ui-carousel#74]
Hi @Learus,

first of all, thanks for open sourcing your solution. I appreciate your work and effort. One question though, can you add a changelog or release tags, please? It helps to see the progress, breaking changes, and other notes about new versions.

That would be very helpful when one decides to upgrade your module or not.

For instance, I use `react-material-ui-carousel@2.0.2` right now and just saw that `react-material-ui-carousel@2.1.1` is available. But without proper documentation of the changes, I can expect or need to take care of, I do not feel safe updating the package.

Please consider my request. Thank you very much.

**Comment by Learus** [comment]
Hello.
This is a great idea, that I haven't really considered in the past. I guess the library is used widely enough to start having a CHANGELOG. Though I am inexperienced with having one, I'll try to do the best I can.

**Comment by natterstefan** [comment]
Hi @Learus,

awesome. Thanks for your feedback. Here's a good starting point: https://keepachangelog.com/en/1.0.0/. Or you take a look at other public packages on GitHub.

**Comment by Learus** [comment]
Sorry for the really late response. The CHANGELOG will be on the next update. Stay tuned!

**Comment by natterstefan** [comment]
Thank you :)

**Comment by Learus** [comment]
Changelog is now added! v2.1.2
