### ISSUE TITLE
Ability to disable swipe motion

### ISSUE THREAD

**Issue by kylemiller3** [Learus/react-material-ui-carousel#77]
My use-case is there exists an underlying object that detects finger drags so I do not want the swipe option enabled. Not sure there is a way to do it other than forking this project. Would you accept a PR that adds this feature?

**Comment by daveteu** [comment]
> My use-case is there exists an underlying object that detects finger drags so I do not want the swipe option enabled. Not sure there is a way to do it other than forking this project. Would you accept a PR that adds this feature?

try onDrag={() => null} on parent div

**Comment by Learus** [comment]
Sorry for the late response. This feature will be added on the next update using a prop named `swipe`. This prop will be `boolean` and will toggle the swiping behavior.
Stay tuned!

**Comment by Learus** [comment]
This feature is implemented from version 2.1.2 onwards.
