### ISSUE TITLE
visible the previous image before hide the current image 

### ISSUE THREAD

**Issue by fadeomar** [Learus/react-material-ui-carousel#8]
I'm using the slider and set theautoPlay to true and the animation to slide and when sliding the images it makes the vertical scroll for a second and disappear but that unwanted behavior, so I figure it out and I found  that the carousel needs for backface-visibility to set for hidden, so for that I'll make a pull request to solve this issue  , you can assign this issue to me

**Comment by Learus** [comment]
Hello, could you perhaps attach a gif or screenshot, so I can understand exactly the problem you're facing?

**Comment by Learus** [comment]
Since there has been no follow-up in some time now, I am closing this. I will reopen if more people face a similar issue.
