### ISSUE TITLE
Thumbnail bar option

### ISSUE THREAD

**Issue by amongabriel** [Learus/react-material-ui-carousel#81]
Hi @Learus ,

First of all congratulations on your work. I want to ask if you intend to implement a thumbnail bar like react-image-gallary:

https://www.linxtion.com/demo/react-image-gallery/
https://github.com/xiaolin/react-image-gallery

Thank you!

**Comment by Learus** [comment]
Hello, and thank you for your kind words.

I have given this idea some thought in the past, and I'm not sure if it would be wise to implement it. You see, this carousel is built to "host" anything inside it, from simple `<img/>` to complicated components with tables and buttons. The question then becomes, how do you create the thumbnails, and what do you display inside them, given that the carousel size and content is variable? The answer to that question is not obvious.

I was thinking of creating another library that implements an image gallery, that works similarly to this one, but that's not something that is currently on my roadmap.
