### ISSUE TITLE
Example not correct - import Button is missing

### ISSUE THREAD

**Issue by ZoharHedri** [Learus/react-material-ui-carousel#82]
Love this package, so thanks!

In your example at Item compoenet your using in Material-ui Button 
But your forgot to import Button  from  @material-ui/core.

So to fix it your can replace that line:
import { Paper } from '@material-ui/core'

In that line:
import { Paper, **Button** } from '@material-ui/core'

Thanks again

**Comment by Learus** [comment]
Fixed. Thanks!
