### ISSUE TITLE
Indicators are not showing up for my <Carousel> use case?

### ISSUE THREAD

**Issue by AndresJaramillo95** [Learus/react-material-ui-carousel#86]
Indicators are not presenting themselves? Please check out this reproducible code. I assume because the Carousel component does not know how many pages to present? In my code below, I've even added a `const [noOfPages]` to solve for this issue. However, I'm not so sure where to use it. 

Then again after looking at your demo code, I'm still unsure why indicators appear for you but not for me. 

https://codesandbox.io/s/spring-rain-oxvq3

**Comment by AndresJaramillo95** [comment]
I'm also assuming this is the same reason why animation props don't work for `fade` and `glide` for my code.

**Comment by Learus** [comment]
Hello.
The reason why the indicators are not showing, and your animations do not work is surprisingly simple. You only specify one child inside the carousel: the `Container`. The Carousel cycles through all of its **direct** children.
For example, indicators and animations will work in this case
```jsx
<Carousel>
    <div>1</div>
    <div>2</div>
    <div>3</div>
</Carousel>
```

but will not work on this one
```jsx
<Carousel>
    <div>
        <div>1</div>
        <div>2</div>
        <div>3</div>
    </div>
</Carousel>
```
since it only has one direct child.
If you could find a way to split your items like this, you wouldn't need to use the `next` and `prev` props to handle changes. Moreover, there is no `onClick` prop. Did you mean `onChange`?

What I would do, is slice the item array into slices of 3 items, and then map each slice to `<Container>` --> `<Grid container>` --> `<Grid item/>` --> ...

**Comment by AndresJaramillo95** [comment]
Thank you for making me understanding what I was doing wrong. I have gotten the animation and identifiers to work by removing the Parent containers. 

However I'm having some issues now with I assume is what you meant by: 

_"slice the item array into slices of 3 items, and then map each slice to <Container> --> <Grid container> --> <Grid item/> -->"_

I would greatly appreciate if you can explain on how I can implement that here:

```JS
          <Carousel
            autoPlay={false}
            onClick={handleChangePage}
            next={loopNext}
            prev={loopPrev}
            NextIcon={<ArrowForwardIosRoundedIcon fontSize='large'/>}
            PrevIcon={<ArrowBackIosRoundedIcon fontSize='large'/>}
            navButtonsProps={{      
              style: {
                  backgroundColor: 'transparent',
                  color:"#447CF0"
              }
            }} 
            indicators={true}
            swipe={true}
            animation="slide"
          >
              {data[0]?.slice((page - 1) * itemsPerPage, page * itemsPerPage)
                .map((data, index) =>
                {
                  return (  
                    <Container key={index} maxWidth="lg" component="main">
                      <Grid container  key={index} alignItemsspacing={5} alignItems="flex-end">
                        <Grid item key={index} xs={4} md={4}>
                            <Card>
                            <CardHeader
                            title={<Chip label={data.symbol} />} 
                            subheader={data.adj_close}        
                            /> 		
                            <CardContent >
                              <MiniGraphs
                                historicalPrice={historicalPrice.filter(i => i.symbol === data.symbol)}
                                dateRange={date}
                              />			
                            </CardContent>
                            </Card>
                        </Grid>
                      </Grid>
                      </Container>
                    );
                })}
          </Carousel>
```

**Comment by Learus** [comment]
Did you by any chance solve your issue?
