### ISSUE TITLE
[Feature Request] Having carousel preload items

### ISSUE THREAD

**Issue by KeithBillings** [Learus/react-material-ui-carousel#88]
In my current project I used this carousel with an item that has to use an API call. Everytime it scrolls to that item, it has to load all over again. Not only does this make me use the API way more than intended, this also causes the component to not display smoothly as it has to load each and every time. 

If the carousel took in its items, and staged loading this would make elements fade into display much smoother. Like if it was on item 1, it would begin to preload item 2.  And on item 2, it would preload item 1 and 3.

**Comment by Learus** [comment]
Fixed in [version 3](https://www.npmjs.com/package/react-material-ui-carousel/v/3.0.2).
