### ISSUE TITLE
[Doubt] Change Default Style

### ISSUE THREAD

**Issue by GiuseppeFantoni** [Learus/react-material-ui-carousel#95]
Is it possible to remove the hover from the next and prev button? Is it possible to also change the size of the lower indicator?

**Comment by Learus** [comment]
Hello @GiuseppeFantoni 

Depends on which hover you want to remove. Specifically, if you want to remove the functionality where hovering on the edges of the carousel reveal the buttons, just specify the `fullHeightHover` prop to false.

If you want to remove or change the hover of the buttons you need to tweak the styles of the buttons. To do that you should specify `navButtonProps={{className: ...}}`. There are more than 1 ways to disable hover styles, but I think the better one in this situation is to override the `:hover` styles with the class given. If you choose to use `style` over `className`, standard react inline style rules apply.

As for the indicator buttons, you can style them similarly to the next and prev buttons. Specifically, you need to specify the `indicatorIconButtonProps`, `activeIndicatorIconButtonProps`, `indicatorContainerProps`. They work exactly like `navButtonProps` as in you can specify inline styles or className. Refer to the [props documentation](https://github.com/Learus/react-material-ui-carousel/blob/master/README.md#props) or in the [indicator customization example section](https://github.com/Learus/react-material-ui-carousel/blob/master/README.md#customizing-the-indicators).
