### ISSUE TITLE
onChange was executed multiple times

### ISSUE THREAD

**Issue by thucltzigvy** [Learus/react-material-ui-carousel#96]
As description, `onChange` was executed multiple times (infinity loop) when I try to click the navigation button fast. This is my case (using `index` and `onChange` props).
```jsx
state = {
  currentInd: 0,
}
handleChangeIndex = (index) => {
  this.setState({currentInd:index});
}

...
<Carousel
  ...
  animation="fade"
  timeout={200}
  autoPlay={false}
  index={this.state.currentInd}
  onChange={this.handleChangeIndex}
/>
...
```

**Comment by littlejustinh** [comment]
I have the same issue. I'm assuming you can't allow them to swipe and use the built in buttons if you want to control the slide with the index prop. 

If my index prop changes, onChange is automatically called immediately after and i get stuck in a loop

**Comment by thucltzigvy** [comment]
So, why this only happened when I click the navigation button fast. I think this's a bug while setting and clearing interval.

**Comment by Learus** [comment]
Hello @thucltzigvy @littlejustinh 

This is working exactly as intended. As the documentation states (paraphrasing):
> the `onChange` is called when the next and previous buttons are pressed, when an indicator is pressed, **or when the index prop changes.**"
That means, exactly what @littlejustinh is describing. 

I'm not sure what exactly you want to do but **supposing you want to know which index is currently active** you could do something like this:

```jsx
const startId = 0;
state = {
  currentInd: startId
}

handleChangeIndex = (index) => {
  this.setState({currentInd:index});
}
...
<Carousel
  ...
  animation="fade"
  timeout={200}
  autoPlay={false}
  index={startId} // <-- Notice this line
  onChange={this.handleChangeIndex}
/>
```
This allows the carousel to fully control indexing. You just have to specify the starting point, and every time the carousel changes, you get the change on your state variable, without having to mess with carousel indexing yourself.

Again, I'm not sure what you want to do, so if that didn't help please elaborate.

**Comment by chris-oms** [comment]
Hi,

I'm having the same issue. I have external elements that control the carousel, so I want to be able to manually change the index viathese external elements, as well as representing changes made when using the carousel nav in these external elements.

So the value passed the the index prop needs to be able to be changed externally of carousel, but clicking twice quickly causes an infinite loop.
