### ISSUE TITLE
React v16 support

### ISSUE THREAD

**Issue by sdemjanenko** [Learus/react-material-ui-carousel#99]
In v2.2.2 the peerDependencies were updated to no longer support any React v16 versions. This should not be done in a patch release. It is also possible to support both versions as peerDependencies: `react": "^16.13.1 || ^17.0.1"`

**Comment by Learus** [comment]
I did exactly as you're proposing and changed the `peerDependencies`  to
```json
"react": "^16.13.1 || ^17.0.1",
"react-dom": "^16.13.1 || ^17.0.1"
```

This should fix the issue. Please upgrade to `v2.3.0`. 
I'm sorry for introducing a breaking change in a patch release. I was not familiar with the convention.
